// Golden conformance: fixtures generated by edge-analyst/scripts/gen-fixtures.mjs (copied
// verbatim from edge-analyst/fixtures/blk3/), with expected outputs computed by running the
// reference implementation (src/blocklist.js) itself over v3 and v4 containers.
// A failure here means the port drifted from the format owner — fix the port, or re-copy the
// fixtures if the format intentionally changed.
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { parseSnapshot, Matcher, HDRS, buildWireEvent, type MatchInput, type MatchResult } from '../src/index.js';

const fx = (f: string) => new URL(`./fixtures/blk3/${f}`, import.meta.url);
const bin = (f: string) => { const b = readFileSync(fx(f)); return new Uint8Array(b.buffer, b.byteOffset, b.byteLength); };
const json = (f: string) => JSON.parse(readFileSync(fx(f), 'utf8'));

interface Expect { block: boolean; challenge: boolean; allowed: boolean; reason: string | null }
interface Case { input: MatchInput; expect: Expect }
const cases = json('cases.json') as Record<'v3' | 'v4', Record<'basic' | 'empty', Case[]>>;
const hdrs = json('hdrs.json') as { hdrs: string[]; cases: Array<{ names: string[]; hm: number }> };

const matcher = (name: string) => new Matcher(parseSnapshot(bin(`${name}.bin`), json(`${name}.meta.json`)));
// The reference reports "nothing matched" as reason null; the port leaves it undefined.
const outcome = (r: MatchResult): Expect => ({ block: r.block, challenge: r.challenge, allowed: r.allowed, reason: r.reason ?? null });

describe.each(['v3', 'v4'] as const)('snapshot matcher conformance (%s)', (version) => {
  const basic = matcher(`${version}-basic`);
  const empty = matcher(`${version}-empty`);

  it.each(cases[version].basic.map((c) => [JSON.stringify(c.input), c] as const))('basic %s', (_label, c) => {
    expect(outcome(basic.match(c.input))).toEqual(c.expect);
  });

  it.each(cases[version].empty.map((c) => [JSON.stringify(c.input), c] as const))('empty %s', (_label, c) => {
    expect(outcome(empty.match(c.input))).toEqual(c.expect);
  });
});

describe('v4 outcomes', () => {
  const basic = matcher('v4-basic');

  it('never sets two outcome flags at once', () => {
    for (const c of [...cases.v4.basic, ...cases.v4.empty]) {
      const r = basic.match(c.input);
      expect(Number(r.allowed) + Number(r.block) + Number(r.challenge)).toBeLessThanOrEqual(1);
    }
  });

  it('carries an allow/challenge outcome the v3 container cannot express', () => {
    const v3 = matcher('v3-basic');
    const pairs = cases.v4.basic.map((c, i) => [c, cases.v3.basic[i]] as const);
    const diverged = pairs.filter(([v4c, v3c]) => JSON.stringify(v4c.expect) !== JSON.stringify(v3c.expect));
    expect(diverged.length).toBeGreaterThan(0);   // the fixtures must actually exercise the new sections
    for (const [v4c, v3c] of diverged) expect(outcome(v3.match(v4c.input))).toEqual(v3c.expect);
  });
});

describe('scratch state', () => {
  it('keeps scratch state per instance (interleaved matchers)', () => {
    const a = matcher('v4-basic');
    const b = matcher('v4-empty');
    // alternate v6 lookups so shared scratch would corrupt one of them
    for (let i = 0; i < 20; i++) {
      expect(a.match({ ip: '2001:db8::1' }).reason).toBe('ip6');
      expect(b.match({ ip: '2001:db8::1' }).block).toBe(false);
      expect(a.match({ ip: '2001:db8::2' }).block).toBe(false);
    }
  });
});

describe('HDRS bitmask conformance', () => {
  it('pins the exact header order', () => {
    expect([...HDRS]).toEqual(hdrs.hdrs);
  });
  it.each(hdrs.cases.map((c) => [c.names.join('+'), c] as const))('hm for %s', (_label, c) => {
    const ev = buildWireEvent(
      { method: 'GET', host: 'x.test', path: '/', query: '', headers: c.names.map((n) => [n, 'v'] as [string, string]), ip: '1.2.3.4' },
      { tap: 'sdk-node', rid: 'r' },
    );
    expect(ev.hm).toBe(c.hm);
  });
});
