// Golden conformance: fixtures generated by edge-analyst/scripts/gen-sdk-fixtures.mjs, with
// expected outputs computed by running the reference implementation (src/blocklist.js) itself.
// A failure here means the port drifted from the format owner — fix the port, or regenerate
// the fixtures if the format intentionally changed.
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { parseSnapshot, Matcher, HDRS, buildWireEvent, type MatchInput } from '../src/index.js';

const fx = (f: string) => new URL(`./fixtures/${f}`, import.meta.url);
const bin = (f: string) => { const b = readFileSync(fx(f)); return new Uint8Array(b.buffer, b.byteOffset, b.byteLength); };
const json = (f: string) => JSON.parse(readFileSync(fx(f), 'utf8'));

interface Case { input: MatchInput; expect: string | null }
const cases = json('cases.json') as { basic: Case[]; empty: Case[] };
const hdrs = json('hdrs.json') as { hdrs: string[]; cases: Array<{ names: string[]; hm: number }> };

describe('snapshot matcher conformance', () => {
  const basic = new Matcher(parseSnapshot(bin('snap-basic.bin'), json('snap-basic.meta.json')));
  const empty = new Matcher(parseSnapshot(bin('snap-empty.bin'), json('snap-empty.meta.json')));

  it.each(cases.basic.map((c) => [JSON.stringify(c.input), c] as const))('basic %s', (_label, c) => {
    const v = basic.match(c.input);
    expect(v.block ? v.reason : null).toBe(c.expect);
  });

  it.each(cases.empty.map((c) => [JSON.stringify(c.input), c] as const))('empty %s', (_label, c) => {
    expect(empty.match(c.input).block).toBe(false);
  });

  it('keeps scratch state per instance (interleaved matchers)', () => {
    const a = new Matcher(parseSnapshot(bin('snap-basic.bin'), json('snap-basic.meta.json')));
    const b = new Matcher(parseSnapshot(bin('snap-empty.bin'), json('snap-empty.meta.json')));
    // alternate v6 lookups so shared scratch would corrupt one of them
    for (let i = 0; i < 20; i++) {
      expect(a.match({ ip: '2001:db8::1' }).reason).toBe('ip6');
      expect(b.match({ ip: '2001:db8::1' }).block).toBe(false);
      expect(a.match({ ip: '2001:db8::2' }).block).toBe(false);
    }
  });
});

describe('HDRS bitmask conformance', () => {
  it('pins the exact header order', () => {
    expect([...HDRS]).toEqual(hdrs.hdrs);
  });
  it.each(hdrs.cases.map((c) => [c.names.join('+'), c] as const))('hm for %s', (_label, c) => {
    const ev = buildWireEvent(
      { method: 'GET', host: 'x.test', path: '/', query: '', headers: c.names.map((n) => [n, 'v'] as [string, string]), ip: '1.2.3.4' },
      { tap: 'sdk-node', rid: 'r' },
    );
    expect(ev.hm).toBe(c.hm);
  });
});
